name: test linux gcc

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log software version
      run: |
        cmake --version
        gcc --version

    - name: Configure CMake with gcc
      run: |
        cmake -S src -B build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Project
      run: |
        cmake --build build

    - name: Run Tests
      run: |
        ctest --test-dir build
